export const ADD_COMPONENT = "ADD_COMPONENT";
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
export const CHANGE_BUN = 'CHANGE_BUN'
export const SORT_COMPONENT = 'SORT_COMPONENT'
export const CLEAR_COMPONENTS = 'CLEAR_COMPONENTS'
